env:
  browser: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules: {
  "no-unused-vars": [ "warn", { "vars": "all", "args": "all", "ignoreRestSiblings": false } ]
}
